In [4]:
import sys
sys.path.append("../../")

import modules
import numpy as np
from sklearn import model_selection, ensemble, metrics

mydata = modules.NT("../../data/b100d30.csv")
x_train, x_test, y_train, y_test = model_selection.train_test_split(mydata.data, mydata.target, test_size=0.4, random_state=508)

[[1.0000e+01 4.9580e+03 2.8000e+01 ... 5.0000e+00 1.4480e+04 6.4088e+04]
 [1.0000e+01 5.7570e+03 2.7000e+01 ... 5.3000e+00 1.4480e+04 6.4088e+04]
 [1.0000e+01 4.5050e+03 3.1000e+01 ... 7.3000e+00 1.4480e+04 6.4088e+04]
 ...
 [1.0000e+01 6.6897e+04 0.0000e+00 ... 9.6100e+01 1.4480e+04 6.4088e+04]
 [1.0000e+01 6.6001e+04 0.0000e+00 ... 9.6100e+01 1.4480e+04 6.4088e+04]
 [1.0000e+01 6.5989e+04 0.0000e+00 ... 9.6100e+01 1.4480e+04 6.4088e+04]]
[4. 4. 4. ... 6. 6. 6.]


In [5]:
clf = ensemble.RandomForestClassifier()
clf.fit(x_train, y_train)

RandomForestClassifier()

In [6]:
y_pred = clf.predict(x_test)
print(metrics.accuracy_score(y_test, y_pred))
print(y_pred, y_test)

0.987037037037037
[3. 5. 2. ... 4. 5. 3.] [3. 5. 2. ... 4. 5. 3.]


4:02